/*
 * Generated by codegen
 * script code:
 *
 * --+HEADER BEGIN
 * #include <stdio.h>
 * --+HEADER END
 *
 * --+P1.C BEGIN
 *     stlPrintf( " P1 Process\n" );
 * --+P1.C END
 * 
 * --+PWAIT
 * 
 * --+P2.C BEGIN
 *     stlPrintf( " P2 Process\n" );
 * --+P2.C END
 * 
 * --+PWAIT
 * 
 * --+C BEGIN
 *     stlPrintf( " Main Process\n" );
 * --+C END
 */

#include <stl.h>                                                               
                                                                               
stlSemaphore gSemaphore[2][2];                                  
stlThread    gThread[2];                                        
                                                                               
/*------------------------------------------------------------------
--+HEADER BEGIN
#include <stdio.h>
--+HEADER END
------------------------------------------------------------------*/
#include <stdio.h>
void * STL_THREAD_FUNC process_P1( stlThread * aThread, void * aArg ); 
void * STL_THREAD_FUNC process_P2( stlThread * aThread, void * aArg ); 
                                                  
stlInt32 main( stlInt32 aArgc, stlChar *aArgv[] ) 
{                                                 
                                  
    stlStatus     sThreadStatus;  
    stlUInt32     sState = 0;     
    stlUInt32     i      = 0;     
    stlUInt32     j      = 0;     
    stlErrorStack sErrorStack;    
                                  
    STL_INIT_ERROR_STACK( &sErrorStack );                                      
                                                                               
    STL_TRY( stlInitialize() == STL_SUCCESS );                                 
    sState = 1;                                                                
                                                                               
    for( i = 0; i < 2; i++ )                                                   
    {                                                                          
        for( j = 0; j < 2; j++ )                                
        {                                                                      
            STL_TRY( stlCreateSemaphore( &gSemaphore[i][j],                    
                                         "SEM",                              
                                         0,                                    
                                         &sErrorStack ) == STL_SUCCESS );      
        }                                                                      
    }                                                                          
                                                                               
    STL_TRY( stlCreateThread( &gThread[1],             
                              NULL,                                   
                              process_P2,                             
                              NULL,                                   
                              &sErrorStack ) == STL_SUCCESS );        
    STL_TRY( stlCreateThread( &gThread[0],             
                              NULL,                                   
                              process_P1,                             
                              NULL,                                   
                              &sErrorStack ) == STL_SUCCESS );        
/*------------------------------------------------------------------
--+PWAIT
------------------------------------------------------------------*/
    STL_TRY( stlReleaseSemaphore( &gSemaphore[0][0], 
                                  &sErrorStack ) == STL_SUCCESS );                 
    STL_TRY( stlAcquireSemaphore( &gSemaphore[1][0], 
                                  &sErrorStack ) == STL_SUCCESS );                 
/*------------------------------------------------------------------
--+PWAIT
------------------------------------------------------------------*/
    STL_TRY( stlReleaseSemaphore( &gSemaphore[0][1], 
                                  &sErrorStack ) == STL_SUCCESS );                 
    STL_TRY( stlAcquireSemaphore( &gSemaphore[1][1], 
                                  &sErrorStack ) == STL_SUCCESS );                 
/*------------------------------------------------------------------
--+C BEGIN
    stlPrintf( " Main Process\n" );
--+C END
------------------------------------------------------------------*/
    stlPrintf( " Main Process\n" );
    for( i = 0; i < 2; i++ )                                    
    {                                                                          
        STL_TRY( stlReleaseSemaphore( &gSemaphore[0][i],                       
                                      &sErrorStack ) == STL_SUCCESS );         
    }                                                                          
                                                                               
    for( i = 0; i < 2; i++ )                                    
    {                                                                          
        STL_TRY( stlJoinThread( &gThread[i],                                   
                                &sThreadStatus,                                
                                &sErrorStack ) == STL_SUCCESS );               
    }                                                                          
                                                                               
    for( i = 0; i < 2; i++ )                                    
    {                                                                          
        STL_TRY( stlDestroySemaphore( &gSemaphore[0][i],                       
                                      &sErrorStack ) == STL_SUCCESS );         
    }                                                                          
                                                                               
    STL_TRY( stlTerminate() == STL_SUCCESS );                                  
                                                                               
    sState = 0;                                                                
                                                                               
    return STL_SUCCESS;                                                        
                                                                               
    STL_FINISH;                                                                
                                                                               
    return STL_FAILURE;                                                        
}                                                                              
                                                                               
                                                      
void * STL_THREAD_FUNC process_P1( stlThread * aThread, void * aArg ) 
{                                                     
    stlErrorStack sErrorStack;     
                                   
    STL_INIT_ERROR_STACK( &sErrorStack );                              
                                                                       
    STL_TRY( stlAcquireSemaphore( &gSemaphore[0][0],    
                                  &sErrorStack ) == STL_SUCCESS );     
                                                                       
/*------------------------------------------------------------------
--+P1.C BEGIN
    stlPrintf( " P1 Process\n" );
--+P1.C END
------------------------------------------------------------------*/
    stlPrintf( " P1 Process\n" );
/*------------------------------------------------------------------
--+PWAIT
------------------------------------------------------------------*/
    STL_TRY( stlReleaseSemaphore( &gSemaphore[1][0], 
                                  &sErrorStack ) == STL_SUCCESS );                 
    STL_TRY( stlAcquireSemaphore( &gSemaphore[0][0], 
                                  &sErrorStack ) == STL_SUCCESS );                 
                                                                              
    STL_TRY( stlExitThread( aThread, 0, &sErrorStack ) == STL_SUCCESS );      
                                                                              
    return NULL;                                                              
                                                                              
    STL_FINISH;                                                               
                                                                              
    return NULL;                                                              
}                                                                             
                                                      
void * STL_THREAD_FUNC process_P2( stlThread * aThread, void * aArg ) 
{                                                     
    stlErrorStack sErrorStack;     
                                   
    STL_INIT_ERROR_STACK( &sErrorStack );                              
                                                                       
    STL_TRY( stlAcquireSemaphore( &gSemaphore[0][1],    
                                  &sErrorStack ) == STL_SUCCESS );     
                                                                       
/*------------------------------------------------------------------
--+P2.C BEGIN
    stlPrintf( " P2 Process\n" );
--+P2.C END
------------------------------------------------------------------*/
    stlPrintf( " P2 Process\n" );
/*------------------------------------------------------------------
--+PWAIT
------------------------------------------------------------------*/
    STL_TRY( stlReleaseSemaphore( &gSemaphore[1][1], 
                                  &sErrorStack ) == STL_SUCCESS );                 
    STL_TRY( stlAcquireSemaphore( &gSemaphore[0][1], 
                                  &sErrorStack ) == STL_SUCCESS );                 
                                                                              
    STL_TRY( stlExitThread( aThread, 0, &sErrorStack ) == STL_SUCCESS );      
                                                                              
    return NULL;                                                              
                                                                              
    STL_FINISH;                                                               
                                                                              
    return NULL;                                                              
}                                                                             
