/*******************************************************************************
 * zle.h
 *
 * Copyright (c) 2011, SUNJESOFT Inc.
 *
 *
 * IDENTIFICATION & REVISION
 *        $Id: zle.h 11918 2014-04-09 08:49:01Z htkim $
 *
 * NOTES
 *    
 *
 ******************************************************************************/

#ifndef _ZLE_H_
#define _ZLE_H_ 1

/**
 * @file zle.h
 * @brief Gliese API Internal Error Routines.
 */

/**
 * @defgroup zle Internal Error Routines
 * @{
 */

#define ZLE_ERRCODE_INVALID_USE_OF_NULL_POINTER STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 0 )

#define ZLE_ERRCODE_INVALID_ATTRIBUTE_OPTION_IDENTIFIER STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 1 )

#define ZLE_ERRCODE_CONNECTION_NOT_OPEN STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 2 )

#define ZLE_ERRCODE_DRIVER_DOES_NOT_SUPPORT_THIS_FUNCTION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 3 )

#define ZLE_ERRCODE_DRIVERS_SQLALLOCHANDLE_ON_SQL_HANDLE_ENV_FAILED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 4 )

#define ZLE_ERRCODE_DRIVERS_SQLALLOCHANDLE_ON_SQL_HANDLE_DBC_FAILED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 5 )

#define ZLE_ERRCODE_CONNECTION_NAME_IN_USE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 6 )

#define ZLE_ERRCODE_INVALID_STRING_OR_BUFFER_LENGTH STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 7 )

#define ZLE_ERRCODE_INVALID_AUTHORIZATION_SPECIFICATION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 8 )

#define ZLE_ERRCODE_FUNCTION_SEQUENCE_ERROR STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 9 )

#define ZLE_ERRCODE_INVALID_CURSOR_STATE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 10 )

#define ZLE_ERRCODE_INVALID_TRANSACTION_OPERATION_CODE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 11 )

#define ZLE_ERRCODE_OPTIONAL_FEATURE_NOT_IMPLEMENTED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 12 )

#define ZLE_ERRCODE_INVALID_APPLICATION_BUFFER_TYPE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 13 )

#define ZLE_ERRCODE_INVALID_DESCRIPTOR_INDEX STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 14 )

#define ZLE_ERRCODE_INVALID_SQL_DATA_TYPE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 15 )

#define ZLE_ERRCODE_INVALID_PARAMETER_TYPE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 16 )

#define ZLE_ERRCODE_INVALID_ARGUMENT_VALUE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 17 )

#define ZLE_ERRCODE_ATTRIBUTE_CANNOT_BE_SET_NOW STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 18 )

#define ZLE_ERRCODE_INVALID_ATTRIBUTE_VALUE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 19 )

#define ZLE_ERRCODE_INVALID_TRANSACTION_STATE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 20 )

#define ZLE_ERRCODE_GENERAL_ERROR STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 21 )

#define ZLE_ERRCODE_PREPARED_STATEMENT_NOT_A_CURSOR_SPECIFICATION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 22 )

#define ZLE_ERRCODE_STRING_DATA_RIGHT_TRUNCATED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 23 )

#define ZLE_ERRCODE_ASSOCIATED_STATEMENT_IS_NOT_PREPARED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 24 )

#define ZLE_ERRCODE_OPTION_TYPE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 25 )

#define ZLE_ERRCODE_INDICATOR_VARIABLE_REQUIRED_BUT_NOT_SUPPLIED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 26 )

#define ZLE_ERRCODE_ERROR_IN_ROW STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 27 )

#define ZLE_ERRCODE_CANNOT_MODIFY_AN_IMPLEMENTATION_ROW_DESCRIPTROR STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 28 )

#define ZLE_ERRCODE_INVALID_DESCRIPTOR_FIELD_IDENTIFIER STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 29 )

#define ZLE_ERRCODE_RESTRICTED_DATA_TYPE_ATTRIBUTE_VIOLATION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 30 )

#define ZLE_ERRCODE_INTERVAL_FIELD_OVERFLOW STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 31 )

#define ZLE_ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 32 )

#define ZLE_ERRCODE_WARNING_STRING_DATA_RIGHT_TRUNCATED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 33 )

#define ZLE_ERRCODE_INVALID_CHARACTER_VALUE_FOR_CAST_SPECIFICATION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 34 )

#define ZLE_ERRCODE_WARNING_FRACTIONAL_TRUNCATION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 35 )

#define ZLE_ERRCODE_DATETIME_FIELD_OVERFLOW STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 36 )

#define ZLE_ERRCODE_INVALID_DATETIME_FORMAT STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 37 )

#define ZLE_ERRCODE_COMMUNICATION_LINK_FAILURE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 38 )

#define ZLE_ERRCODE_INTERNAL_DATA_TYPE_IS_INVALID STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 39 )

#define ZLE_ERRCODE_INVALID_CURSOR_NAME STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 40 )

#define ZLE_ERRCODE_FAILED_TO_ATOMIC_EXECUTION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 41 )

#define ZLE_ERRCODE_INVALID_DRIVER_COMPLETION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 42 )

#define ZLE_ERRCODE_DRIVER_KEYWORD_SYNTAX_ERROR STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 43 )

#define ZLE_ERRCODE_CLIENT_UNABLE_TO_ESTABLISH_CONNECTION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 44 )

#define ZLE_ERRCODE_INFORMATION_TYPE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 45 )

#define ZLE_ERRCODE_DATA_SOURCE_NOT_FOUND_AND_NO_DEFAULT_DRIVER_SPECIFIED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 46 )

#define ZLE_ERRCODE_FETCH_TYPE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 47 )

#define ZLE_ERRCODE_UNIQUENESS_OPTION_TYPE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 48 )

#define ZLE_ERRCODE_ACCURACY_OPTION_TYPE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 49 )

#define ZLE_ERRCODE_COLUMN_TYPE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 50 )

#define ZLE_ERRCODE_SCOPE_TYPE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 51 )

#define ZLE_ERRCODE_NULLABLE_TYPE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 52 )

#define ZLE_ERRCODE_INCONSISTENT_DESCRIPTOR_INFORMATION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 53 )

#define ZLE_ERRCODE_WARNING_OPTION_VALUE_CHANGED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 54 )

#define ZLE_ERRCODE_INVALID_CURSOR_POSITION STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 55 )

#define ZLE_ERRCODE_ROW_VALUE_OUT_OF_RANGE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 56 )

#define ZLE_ERRCODE_TIMEOUT_EXPIRED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 57 )

#define ZLE_ERRCODE_INVALID_CHARACTER_SET_NAME STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 58 )

#define ZLE_ERRCODE_ATTEMPT_TO_CONCATENATE_A_NULL_VALUE STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 59 )

#define ZLE_ERRCODE_NON_CHARACTER_AND_NON_BINARY_DATA_SENT_IN_PIECES STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 60 )

#define ZLE_ERRCODE_INVALID_ODBC_INI STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 61 )

#define ZLE_ERRCODE_DIALOG_FAILED STL_MAKE_ERRCODE( STL_ERROR_MODULE_GLIESE_LIBRARY_AODBC, 62 )

#define ZLE_MAX_ERROR     63

/** @} */

#endif /* _ZLE_H_ */
